config/routes.rb
Store::Application.routes.draw do
  
  get "finder/poster"

  get "finder/mug"

  get "finder/tshirt"

  resources :lineitems

  resources :orders

  resources :customers

  resources :provinces

  namespace :admin do
    resources :products, :provinces
  end
  
  resources :products
  match 'finder/poster'=> 'finder#poster', :as => 'poster', :via => :get
  match 'finder/mug'=> 'finder#mug', :as => 'mug', :via => :get
  match 'finder/tshirt'=> 'finder#tshirt', :as => 'tshirt', :via => :get
  match "results" => "finder#search_results", :as => 'results', :via => :post
  

end

app/models/province.rb
class Province < ActiveRecord::Base
  attr_accessible :pst, :gst, :hst
  validates :name, :pst, :gst, :hst, :presence => true
  
  has_many :customers
end

app/controllers/admin/provinces_controller.rb
class Admin::ProvincesController < ApplicationController
  # GET /provinces
  # GET /provinces.json
  def index
    @provinces = Province.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @provinces }
    end
  end

  # GET /provinces/1
  # GET /provinces/1.json
  def show
    @province = Province.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @province }
    end
  end

  # GET /provinces/new
  # GET /provinces/new.json
  def new
    @province = Province.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @province }
    end
  end

  # GET /provinces/1/edit
  def edit
    @province = Province.find(params[:id])
  end

  # POST /provinces
  # POST /provinces.json
  def create
    @province = Province.new(params[:province])

    respond_to do |format|
      if @province.save
        format.html { redirect_to @province, notice: 'Province was successfully created.' }
        format.json { render json: @province, status: :created, location: @province }
      else
        format.html { render action: "new" }
        format.json { render json: @province.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /provinces/1
  # PUT /provinces/1.json
  def update
    @province = Province.find(params[:id])

    respond_to do |format|
      if @province.update_attributes(params[:province])
        format.html { redirect_to @province, notice: 'Province was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @province.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /provinces/1
  # DELETE /provinces/1.json
  def destroy
    @province = Province.find(params[:id])
    @province.destroy

    respond_to do |format|
      format.html { redirect_to provinces_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/provinces_controller.rb
class ProvincesController < ApplicationController
  # GET /provinces
  # GET /provinces.json
  def index
    @provinces = Province.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @provinces }
    end
  end

  # GET /provinces/1
  # GET /provinces/1.json
  def show
    @province = Province.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @province }
    end
  end

  # GET /provinces/new
  # GET /provinces/new.json
  def new
    @province = Province.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @province }
    end
  end

  # GET /provinces/1/edit
  def edit
    @province = Province.find(params[:id])
  end

  # POST /provinces
  # POST /provinces.json
  def create
    @province = Province.new(params[:province])

    respond_to do |format|
      if @province.save
        format.html { redirect_to @province, notice: 'Province was successfully created.' }
        format.json { render json: @province, status: :created, location: @province }
      else
        format.html { render action: "new" }
        format.json { render json: @province.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /provinces/1
  # PUT /provinces/1.json
  def update
    @province = Province.find(params[:id])

    respond_to do |format|
      if @province.update_attributes(params[:province])
        format.html { redirect_to @province, notice: 'Province was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @province.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /provinces/1
  # DELETE /provinces/1.json
  def destroy
    @province = Province.find(params[:id])
    @province.destroy

    respond_to do |format|
      format.html { redirect_to provinces_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/provinces_helper.rb
module ProvincesHelper
end

app/views/admin/provinces/_form.html.erb
<%= form_for(@province) do |f| %>
  <% if @province.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@province.errors.count, "error") %> prohibited this province from being saved:</h2>

      <ul>
      <% @province.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :pst %><br />
    <%= f.text_field :pst %>
  </div>
  <div class="field">
    <%= f.label :gst %><br />
    <%= f.text_field :gst %>
  </div>
  <div class="field">
    <%= f.label :hst %><br />
    <%= f.text_field :hst %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/provinces/edit.html.erb
<h1>Editing province</h1>

<%= render 'form' %>

<%= link_to 'Show', @province %> |
<%= link_to 'Back', admin_provinces_path %>

app/views/admin/provinces/index.html.erb
<h1>Listing provinces</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Pst</th>
    <th>Gst</th>
    <th>Hst</th>
    <th></th>
    <th></th>
  </tr>

<% @provinces.each do |province| %>
  <tr>
    <td><%= province.name %></td>
    <td><%= province.pst %></td>
    <td><%= province.gst %></td>
    <td><%= province.hst %></td>
    <td><%= link_to 'Edit', edit_admin_province_path(province) %></td>
    <td><%= link_to 'Destroy', province, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<!--<%= link_to 'New Province', new_province_path %>-->

app/views/admin/provinces/new.html.erb
<h1>New province</h1>

<%= render 'form' %>

<%= link_to 'Back', provinces_path %>

app/views/admin/provinces/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @province.name %>
</p>

<p>
  <b>Pst:</b>
  <%= @province.pst %>
</p>

<p>
  <b>Gst:</b>
  <%= @province.gst %>
</p>

<p>
  <b>Hst:</b>
  <%= @province.hst %>
</p>


<%= link_to 'Edit', edit_province_path(@province) %> |
<%= link_to 'Back', provinces_path %>