config/routes.rb
Store::Application.routes.draw do
  
  get "finder/poster"

  get "finder/mug"

  get "finder/tshirt"

  resources :lineitems

  resources :orders

  resources :customers

  resources :provinces

  namespace :admin do
    resources :products, :provinces
  end
  
  resources :products
  match 'finder/poster'=> 'finder#poster', :as => 'poster', :via => :get
  match 'finder/mug'=> 'finder#mug', :as => 'mug', :via => :get
  match 'finder/tshirt'=> 'finder#tshirt', :as => 'tshirt', :via => :get
  match "results" => "finder#search_results", :as => 'results', :via => :post
  

end

app/models/product.rb
class Product < ActiveRecord::Base
  validates :product_name, :description, :price, :quantity, :presence => true
  
  has_many :lineitems
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  # GET /products
  # GET /products.json
  
  before_filter :require_sudo#password, application_controller
  
  
  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end
  
  def admin
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new
    #@categories = Category.order(:name)

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
    #@categories = Category.order(:name)
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])
    

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  # GET /products.json
  
  before_filter :require_sudo, :except => [:index, :show] #password, application_controller
  
  
  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end
  
  def admin
    @products = Product.all
    @categories = Category.order(:name)
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_name %><br />
    <%= f.text_field :product_name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br />
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :category %><br />
    <%= f.text_field :category %>
    
    <!--< f.collection_select :category, @categories, :id, :name %>< f.select :category, Product::ALLOWED_CATEGORY%> put that constant in the controller-->
  </div>
  <div class="field">
    <%= f.label :image %><br />
    <%= f.text_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/admin/products/index.html.erb
<h3><%= link_to 'Provinces', admin_provinces_path %></h3>
<h3><%= link_to 'New Product', new_admin_product_path %></h3>

<table>
  <tr>
  <% counter = 1 %>
  <% @products.each do |product| %>
  <td>
    <%if product.image.present?%>
    <p><%= image_tag product.image %></p>
    <%else%>
      <p><img src="/assets/image_not_found.jpg" alt="Keep Calm Inc."/></p>
    <%end%>
    <!--<p><%= product.product_name %></p>-->
    <p><%= link_to product.description, product_path(product) %></p>
    <p>$<%= product.price %></p>
    <p>Quantity: <%= product.quantity %></p>
    <p>Category: <%= product.category %></p>
    <p><%= link_to 'Edit', edit_admin_product_path(product) %> <%= link_to 'Destroy', product, confirm: 'Are you sure?', method: :delete %></p>
  </td>
  <%counter += 1%>
  <% if(counter == 4)%>
    <%counter = 1%>
    </tr>
    <tr>
  <%end%>
<% end %>
</table>
<br />

app/views/admin/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/admin/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Product name:</b>
  <%= @product.product_name %>
</p>

<p>
  <b>Description:</b>
  <%= @product.description %>
</p>

<p>
  <b>Price:</b>
  <%= @product.price %>
</p>

<p>
  <b>Quantity:</b>
  <%= @product.quantity %>
</p>

<p>
  <b>Category:</b>
  <%= @product.category %>
</p>

<p>
  <b>Image:</b>
  <%= @product.image %>
</p>


<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>