config/routes.rb
Store::Application.routes.draw do
  
  get "finder/poster"

  get "finder/mug"

  get "finder/tshirt"

  resources :lineitems

  resources :orders

  resources :customers

  resources :provinces

  namespace :admin do
    resources :products, :provinces
  end
  
  resources :products
  match 'finder/poster'=> 'finder#poster', :as => 'poster', :via => :get
  match 'finder/mug'=> 'finder#mug', :as => 'mug', :via => :get
  match 'finder/tshirt'=> 'finder#tshirt', :as => 'tshirt', :via => :get
  match "results" => "finder#search_results", :as => 'results', :via => :post
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Keep Calm Inc.</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <article>
    <header>
      <div id="top">
        <h5><%= link_to 'Admin', admin_products_path %></h5>
        <h3>Cart: (item count) as link</h3>
      </div>
    </header>
  </article>
  <div id="container">
    <div id="header">
      <img src="/assets/header.png" alt="Keep Calm Inc."/>
    </div>
    <div id="nav">
      <ul>
        <li><%= link_to 'All Products', products_path %></li>
        <li><%= link_to 'Posters', finder_poster_path %></li>
        <li><%= link_to 'Mugs', finder_mug_path %></li>
        <li><%= link_to 'T-Shirts', finder_tshirt_path %></li>
        <li>
          <%= form_tag results_path do %>
            <%= text_field_tag :keyword %>
            <%= submit_tag "Search" %>
          <%end%>
        </li>
      </ul>
    </div>
    <div id="content">
    <%= yield %>
    </div>
    <footer>
      <p><strong>Copyright </strong>2012 Tori Froese</p>
    </footer>
  </div>
</body>
</html>